# Generated by Django 2.2.28 on 2022-11-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressgjjgpbfhue'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressgjjgpbfhue',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
